// Copyright (c) 2026 Jonathan Embley-Riches. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "CoreMinimal.h"
#include "Misc/AutomationTest.h"

#include "MuJoCo/Components/Actuators/MjActuator.h"
#include "MuJoCo/Components/Sensors/MjSensor.h"
#include "MuJoCo/Components/Joints/MjJoint.h"
#include "MuJoCo/Components/Geometry/MjGeom.h"
#include "MuJoCo/Components/Geometry/MjSite.h"
#include "MuJoCo/Components/Tendons/MjTendon.h"
#include "MuJoCo/Components/Constraints/MjEquality.h"
#include "MuJoCo/Components/Sensors/MjCamera.h"
#include "MuJoCo/Components/Deformable/MjFlexcomp.h"
#include "MuJoCo/Components/Bodies/MjBody.h"
#include "MuJoCo/Components/Bodies/MjFrame.h"
#include "MuJoCo/Components/Physics/MjInertial.h"
#include "MuJoCo/Components/Physics/MjContactPair.h"
#include "MuJoCo/Components/Physics/MjContactExclude.h"

#include "MjSchemaForTests.h"

// T3: codegen completeness. For every category, the schema-mirrored list of
// UPROPERTY names (autogenerated into MjSchemaForTests.h by the same codegen
// run that emits the components) must match real UPROPERTY decls on the
// corresponding UClass. This catches schema drift, rename mistakes, accidental
// exclude_attrs, and missing bOverride_X toggles in a single sweep.

namespace
{
bool CheckPropList(FAutomationTestBase& Test, UClass* Cls, const TArray<FString>& Props, const TCHAR* CategoryLabel)
{
	bool bAllOk = true;
	for (const FString& Prop : Props)
	{
		FName PropName(*Prop);
		if (Cls->FindPropertyByName(PropName) == nullptr)
		{
			Test.AddError(FString::Printf(TEXT("[%s] missing UPROPERTY '%s' on %s"),
				CategoryLabel, *Prop, *Cls->GetName()));
			bAllOk = false;
		}

		const FString ToggleName = FString::Printf(TEXT("bOverride_%s"), *Prop);
		FName ToggleFName(*ToggleName);
		// Canonicalised properties (Pos / Quat) have bOverride_Pos / bOverride_Quat;
		// others have bOverride_<lowercase>. Either way, the toggle must exist.
		if (Cls->FindPropertyByName(ToggleFName) == nullptr)
		{
			Test.AddError(FString::Printf(TEXT("[%s] missing toggle '%s' on %s"),
				CategoryLabel, *ToggleName, *Cls->GetName()));
			bAllOk = false;
		}
	}
	return bAllOk;
}
} // namespace

#define URLAB_CODEGEN_COMPLETENESS_TEST(TestName, ClsName, PropFnName, Label)     \
	IMPLEMENT_SIMPLE_AUTOMATION_TEST(FCodegenCompleteness_##TestName,             \
		"URLab.Codegen.Completeness." #TestName,                                  \
		EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter) \
	bool FCodegenCompleteness_##TestName::RunTest(const FString&)                 \
	{                                                                             \
		UClass* Cls = ClsName::StaticClass();                                     \
		const TArray<FString>& Props = URLabCodegenSchemaForTests::PropFnName();  \
		return CheckPropList(*this, Cls, Props, TEXT(Label));                     \
	}

URLAB_CODEGEN_COMPLETENESS_TEST(Actuator, UMjActuator, ActuatorProps, "actuator")
URLAB_CODEGEN_COMPLETENESS_TEST(Sensor, UMjSensor, SensorProps, "sensor")
URLAB_CODEGEN_COMPLETENESS_TEST(Joint, UMjJoint, JointProps, "joint")
URLAB_CODEGEN_COMPLETENESS_TEST(Site, UMjSite, SiteProps, "site")
URLAB_CODEGEN_COMPLETENESS_TEST(Tendon, UMjTendon, TendonProps, "tendon")
URLAB_CODEGEN_COMPLETENESS_TEST(Equality, UMjEquality, EqualityProps, "equality")
URLAB_CODEGEN_COMPLETENESS_TEST(Geom, UMjGeom, GeomProps, "geom")
URLAB_CODEGEN_COMPLETENESS_TEST(Camera, UMjCamera, CameraProps, "camera")
URLAB_CODEGEN_COMPLETENESS_TEST(Flexcomp, UMjFlexcomp, FlexcompProps, "flexcomp")
URLAB_CODEGEN_COMPLETENESS_TEST(Body, UMjBody, BodyProps, "body")
URLAB_CODEGEN_COMPLETENESS_TEST(Frame, UMjFrame, FrameProps, "frame")
URLAB_CODEGEN_COMPLETENESS_TEST(Inertial, UMjInertial, InertialProps, "inertial")
URLAB_CODEGEN_COMPLETENESS_TEST(ContactPair, UMjContactPair, Contact_PairProps, "contact.pair")
URLAB_CODEGEN_COMPLETENESS_TEST(ContactExclude, UMjContactExclude, Contact_ExcludeProps, "contact.exclude")

#undef URLAB_CODEGEN_COMPLETENESS_TEST
